// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLnmf43wheWggfmE0O0LAyXHnYRbkegk',
    appId: '1:1573846617:web:9f074a341538e96de03b48',
    messagingSenderId: '1573846617',
    projectId: 'pr-8-chat-app',
    authDomain: 'pr-8-chat-app.firebaseapp.com',
    storageBucket: 'pr-8-chat-app.appspot.com',
    measurementId: 'G-P0PNEGPXRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBihTqf6Rp2RK02UIl7MvKQxbvuOsYWioE',
    appId: '1:1573846617:android:ff7077ab295ca914e03b48',
    messagingSenderId: '1573846617',
    projectId: 'pr-8-chat-app',
    storageBucket: 'pr-8-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDM6mNaWU8aWbEguMbcpHyyGoVyXFBkO8',
    appId: '1:1573846617:ios:d41a70e3ac8469a5e03b48',
    messagingSenderId: '1573846617',
    projectId: 'pr-8-chat-app',
    storageBucket: 'pr-8-chat-app.appspot.com',
    iosBundleId: 'com.example.pr8ChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDM6mNaWU8aWbEguMbcpHyyGoVyXFBkO8',
    appId: '1:1573846617:ios:d41a70e3ac8469a5e03b48',
    messagingSenderId: '1573846617',
    projectId: 'pr-8-chat-app',
    storageBucket: 'pr-8-chat-app.appspot.com',
    iosBundleId: 'com.example.pr8ChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALLnmf43wheWggfmE0O0LAyXHnYRbkegk',
    appId: '1:1573846617:web:b3b750dd2afa03f6e03b48',
    messagingSenderId: '1573846617',
    projectId: 'pr-8-chat-app',
    authDomain: 'pr-8-chat-app.firebaseapp.com',
    storageBucket: 'pr-8-chat-app.appspot.com',
    measurementId: 'G-3ZXQ3GYLED',
  );
}
